### ISSUE TITLE
Saknas tag funktionalitet

### ISSUE THREAD

**Issue by rs222kn** [js223kz/1DV450_BIRDSPOTTER_JS223KZ#8]
I minimum kravet står det att en inloggad användare ska kunna skapa taggar för sinna händelser detta är en funktionalitet som helt saknas då den inte finns med i api:et eller databasen.

"En inloggad användare som kan skapa händelser kan också skapa taggar för dessa händelser."

**Comment by js223kz** [comment]
Fåglarna är mina taggar. Har fixat det nu.
